# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

# default: production
version: production

application: decruiter
runtime: python27
api_version: 1
threadsafe: yes


inbound_services:
# https://cloud.google.com/appengine/docs/python/mail/receiving-mail-with-mail-api
# Enable mail services
- mail
- mail_bounce


# Handlers define how to route requests to your application.
handlers:

  #
  # Mail Handlers
  #
- url: /_ah/mail/.+
  script: mail_handler.app
  login: admin
  
  #
  # Recruiter Emails Controller Endpoints
  #
- url: /admin/recruitments(/.*)?
  script: controllers.recruiter_emails.app
  login: admin
  
- url: /admin/recruitment(/.*)?
  script: controllers.recruiter_emails.app
  login: admin

  #
  # Default Route
  #
- url: .* 
  script: controllers.pages.app


# TODO: List any other App Engine SDK libs you may need here.
# See https://developers.google.com/appengine/docs/python/tools/libraries27
#libraries:
#- name: jinja2
#  version: latest
